version: '2'
services:
  app:
    image: mgrigoriev/items_app
    environment:
      - DB_HOST=db
      - RAILS_ENV=production
    ports:
      - 3000:3000

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=items_app_production
    volumes:
      - ../tmp/db/production:/var/lib/postgresql/data
    ports:
      - 5431:5432

