version: '2'
services:
  app:
    image: mgrigoriev/items_app
    environment:
      - DB_HOST=db
      - RAILS_ENV=development
    ports:
      - 80:3000

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=items_app_development
    volumes:
      - ../tmp/db/development:/var/lib/postgresql/data
    ports:
      - 5431:5432
